import {
  border,
  Box,
  Flex,
  Icon,
  InputRightAddon,
  InputRightElement,
  Stack,
  useTheme,
} from "@chakra-ui/react";
import { AiOutlineEyeInvisible, AiOutlineEye } from "react-icons/ai";
import { SyntheticEvent, useState } from "react";
import Head from "next/head";
import { useFormik } from "formik";
import * as yup from "yup";
import FormInput from "@/components/Forms/FormInput";
import HeaderTag from "@/components/HeaderTag";
import Layout from "@/components/Layout";
import Wrapper from "@/components/Wrapper";
import { Btn } from "@/components/Button";
import { FaChevronRight } from "react-icons/fa";
import { BsCheckCircle } from "react-icons/bs";

function createnew() {
  const theme = useTheme();
  const { black, white } = theme.colors.brand;
  const [passwordVisible, setPasswordVisible] = useState(false);

  const validationSchema = yup.object().shape({
    new_password: yup.string().trim().required("Password is required"),
    password_confirmation: yup
      .string()
      .oneOf([yup.ref("new_password"), null], "Password does not match")
      .required("Password Confirmation is required"),
  });

  const {
    handleSubmit,
    handleChange,
    handleBlur,
    isSubmitting,
    errors,
    touched,
  } = useFormik({
    initialValues: {
      new_password: "",
      password_confirmation: "",
    },
    validationSchema,
    onSubmit: async (values, formikHelpers) => {
      console.log(values);
    },
  });

  const togglePasswordVisiblity = (e: SyntheticEvent) => {
    e.preventDefault();
    setPasswordVisible(!passwordVisible);
  };

  return (
    <div>
      <Head>
        <title>Create Account - Amahlubi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Wrapper>
          <Flex
            justifyContent="center"
            alignItems="center"
            flexDir="column"
            pos="relative"
            zIndex={1}
          >
            <HeaderTag mb="1.8rem" fontWeight="600" letterSpacing="unset">
              Setup new password
            </HeaderTag>
            <Box
              bg="whiteAlpha.900"
              px="3.2rem"
              py="7rem"
              borderRadius="2xl"
              maxW="60.3rem"
              w="100%"
              mt="3rem"
            >
              <HeaderTag
                mt="unset"
                letterSpacing="unset"
                fontSize="1.7rem"
                mb="1.8rem"
                fontWeight="600"
                color={black}
              >
                Enter your new password
              </HeaderTag>
              <form onSubmit={handleSubmit}>
                <Stack spacing="3.7rem">
                  <Flex
                    alignItems="center"
                    flexDir={["column", "column", "column", "row"]}
                  >
                    <FormInput
                      containerProps={{
                        flexDir: "column",
                        mx: "2rem",
                      }}
                      labelProps={{
                        alignSelf: "flex-start",
                        borderRight: "unset",
                        fontSize: "1.1rem",
                        fontWeight: "800",
                      }}
                      inputProps={{
                        id: "new_password",
                        name: "new_password",
                        onChange: handleChange,
                        onBlur: handleBlur,
                        isInvalid:
                          !!errors.new_password && touched.new_password,
                        placeholder: "New password",
                        type: passwordVisible ? "text" : "password",
                        borderRadius: "md",
                        border: `1px solid ${black} !important`,
                        p: "2.3rem",
                        color: black,
                        _placeholder: {
                          color: black,
                          fontWeight: "bold",
                        },
                      }}
                      formErrorMessage={errors.new_password}
                      inputRightAddon={
                        <InputRightElement
                          onClick={(e) => togglePasswordVisiblity(e)}
                          as="button"
                          height="100%"
                          mr="1rem"
                          bg="transparent"
                          color={black}
                          children={
                            passwordVisible ? (
                              <AiOutlineEyeInvisible size="2rem" />
                            ) : (
                              <AiOutlineEye size="2rem" />
                            )
                          }
                        />
                      }
                    />
                  </Flex>

                  <Flex
                    alignItems="center"
                    flexDir={["column", "column", "column", "row"]}
                  >
                    <FormInput
                      containerProps={{
                        flexDir: "column",
                        mx: "2rem",
                      }}
                      labelProps={{
                        alignSelf: "flex-start",
                        borderRight: "unset",
                        fontSize: "1.1rem",
                        fontWeight: "800",
                      }}
                      inputProps={{
                        id: "password_confirmation",
                        name: "password_confirmation",
                        onChange: handleChange,
                        onBlur: handleBlur,
                        isInvalid:
                          !!errors.password_confirmation &&
                          touched.password_confirmation,
                        placeholder: "Retype password",
                        type: passwordVisible ? "text" : "password",
                        borderRadius: "md",
                        border: `1px solid ${black} !important`,
                        p: "2.3rem",
                        color: black,
                        _placeholder: {
                          color: black,
                          fontWeight: "bold",
                        },
                      }}
                      formErrorMessage={errors.password_confirmation}
                      inputRightAddon={
                        <InputRightElement
                          onClick={(e) => togglePasswordVisiblity(e)}
                          as="button"
                          height="100%"
                          mr="1rem"
                          bg="transparent"
                          color={black}
                          children={
                            passwordVisible ? (
                              <AiOutlineEyeInvisible size="2rem" />
                            ) : (
                              <AiOutlineEye size="2rem" />
                            )
                          }
                        />
                      }
                    />
                  </Flex>

                  <Flex justifyContent="center">
                    <Btn
                      isLoading={isSubmitting}
                      type="submit"
                      fontFamily="Roboto"
                      fontWeight="400"
                      borderRadius="lg"
                      fontSize="1.2rem"
                      maxW="20.6rem"
                      w="100%"
                      textAlign="center"
                      bgColor={black}
                      color={white}
                      border={black}
                      px="1.8rem"
                      py="1.5rem"
                      // _hover={{ backgroundColor: "black", opacity: ".7" }}
                      rightIcon={<Icon as={FaChevronRight} />}
                    >
                      Set new password
                    </Btn>
                  </Flex>
                </Stack>
              </form>
              <Flex alignItems="center" justifyContent="center" gap=".5rem">
                <Icon color={black} as={BsCheckCircle} mt=".8rem" />
                <HeaderTag
                  color={black}
                  letterSpacing="unset"
                  as="h3"
                  fontSize="1.4rem"
                  fontFamily="Montserrat"
                  mb="2rem"
                >
                  Check your email to continue with recovery
                </HeaderTag>
              </Flex>
            </Box>
          </Flex>
        </Wrapper>
      </Layout>
    </div>
  );
}

export default createnew;
