import { border, Box, Flex, InputLeftAddon, InputRightAddon, Stack, useTheme } from "@chakra-ui/react"
import {AiOutlineEyeInvisible ,AiOutlineEye } from 'react-icons/ai'
import { SyntheticEvent, useState } from "react"
import  Head  from "next/head"
import FormInput from "@/components/Forms/FormInput"
import HeaderTag from "@/components/HeaderTag"
import Layout from "@/components/Layout"
import Wrapper from "@/components/Wrapper"
import { Btn } from "@/components/Button"
import Link from "next/link"


function reset() {
  const theme = useTheme()
  const { black, metallicSunburst } = theme.colors.brand
  const [passwordVisible, setPasswordVisible ] = useState(false)

  const togglePasswordVisiblity = (e: SyntheticEvent) => {
      e.preventDefault()
      setPasswordVisible(!passwordVisible)
  }

  return (
    <div>
      <Head>
        <title>Create Account - Amahlubi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
          <Wrapper>
                <Flex justifyContent='center' alignItems='center' flexDir='column' pos='relative' zIndex={1} >
                    <HeaderTag mb='1.8rem' fontWeight='600' letterSpacing='unset'>
                        Recover password
                    </HeaderTag>
                    <Box bg={black} px='3.2rem' py='7rem' borderRadius='md' maxW='48.3rem' w='100%' >
                      <HeaderTag mt='unset' letterSpacing='unset' textAlign='left' fontSize='1.7rem' mb='1.8rem' fontWeight='600'>
                         Reset password
                      </HeaderTag>
                      <form>
                          <Stack spacing='1.7rem'>
                              <Flex alignItems='center' flexDir={['column', 'column', 'column', 'row']}>
                                  <FormInput label="Email Address" 
                                  containerProps={{
                                    flexDir: 'column'
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'email',
                                    type:'email',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    p: '2.5rem'
                                  }}
                                  />
                              </Flex>

                              <Flex  flexDir='column'>
                              
                                  <Btn mt={['1.5rem', '1.5rem', '1.5rem', '0']}   size='lg' type='submit'>Send Reset Link</Btn>
                              </Flex>
                          </Stack>
                      </form>

                    </Box>
                </Flex>
          </Wrapper>
      </Layout>
    </div>
  )
}

export default reset