import Head from 'next/head'
import ContactSection from '@/components/ContactSection'
import Footer from '@/components/Footer'
import Layout from '@/components/Layout'
import Search from '@/components/Search'

export default function Home():JSX.Element {
  return (
    <div>
      <Head>
        <title>Categories </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <>
          <Search />
          <ContactSection />
          <Footer />
          </>
      </Layout>
    </div>
  )
}
