import { border, Box, Flex, InputLeftAddon, InputRightAddon, Stack, useTheme } from "@chakra-ui/react"
import {AiOutlineEyeInvisible ,AiOutlineEye } from 'react-icons/ai'
import { SyntheticEvent, useState } from "react"
import  Head  from "next/head"
import FormInput from "../components/Forms/FormInput"
import FormSelect from "../components/Forms/FormSelect"
import HeaderTag from "../components/HeaderTag"
import Layout from "../components/Layout"
import Wrapper from "../components/Wrapper"
import { Btn } from "../components/Button"
import Link from "next/link"


function createaccount() {
  const theme = useTheme()
  const { black, metallicSunburst } = theme.colors.brand
  const [passwordVisible, setPasswordVisible ] = useState(false)

  const togglePasswordVisiblity = (e: SyntheticEvent) => {
      e.preventDefault()
      setPasswordVisible(!passwordVisible)
  }

  return (
    <div>
      <Head>
        <title>Create Account - Amahlubi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
          <Wrapper>
                <Flex justifyContent='center' alignItems='center' flexDir='column' pos='relative' zIndex={1} >
                    <HeaderTag mb='1.8rem' fontWeight='600' letterSpacing='unset'>
                        Join the Community.
                    </HeaderTag>
                    <Box bg={black} padding='1.2rem 3.2rem' borderRadius='md' maxW='61.3rem' w='100%' >
                      <HeaderTag mt='unset' letterSpacing='unset' textAlign='left' fontSize='1.7rem' mb='1.8rem' fontWeight='600'>
                          Profile Details
                      </HeaderTag>
                      <form>
                          <Stack spacing='1.7rem'>
                              <Flex alignItems='center' flexDir={['column', 'column', 'column', 'row']}>
                                  <FormInput label="First Name" 
                                  containerProps={{
                                    flexDir: 'column',
                                    mr:['0','0','0','3.9rem']
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'first-name',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    p: '2rem'
                                  }}
                                  />
                                  <FormInput 
                                  label="Last Name" 
                                  containerProps={{
                                    flexDir: 'column'
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'last-name',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    p: '2rem'
                                  }}
                                  />
                              </Flex>
                   
                              <Flex alignItems='center' flexDir={['column', 'column', 'column', 'row']}>
                                  <FormInput label="Email Address" 
                                  containerProps={{
                                    flexDir: 'column',
                                    mr:['0','0','0','3.9rem']
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'email',
                                    type:'email',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    p: '2rem'
                                  }}
                                  />
                                  <FormInput 
                                  label="Mobile" 
                                  containerProps={{
                                    flexDir: 'column'
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'mobile',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    p: '2rem'
                                  }}
                                  inputLeftAddon= {
                                  <InputLeftAddon  
                                  height='inherit'
                                  border={`2px solid ${metallicSunburst} !important`} 
                                  bg='transparent' 
                                  children='+27' 
                                  />
                                }
                                  />
                              </Flex>

                              <Flex alignItems='center' flexDir={['column', 'column', 'column', 'row']}>
                                  <FormSelect label="Country" 
                                  containerProps={{
                                    flexDir: 'column',
                                    mr:['0','0','0','3.9rem']
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  selectProps={{
                                    id:'country',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    size: 'lg',
                                    sx:{
                                      '&.chakra-select': {
                                        height: '4.4rem'
                                      }
                                    }
                                  }}
                                  >
                                      <option value='1'> coutry 1</option>
                                      <option value='2'> country 2</option>
                                  </FormSelect>
                                  <FormInput 
                                  label="Password" 
                                  containerProps={{
                                    flexDir: 'column'
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'password',
                                    type: passwordVisible ? 'text' : 'password',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    borderRight:'none !important',
                                    p: '2rem'
                                  }}
                                  inputRightAddon= {
                                  <InputRightAddon  
                                  onClick={(e) => togglePasswordVisiblity(e)}
                                  as='button'
                                  height='inherit'
                                  border={`2px solid ${metallicSunburst} !important`} 
                                  borderLeft='none !important'
                                  bg='transparent' 
                                  children={passwordVisible ? <AiOutlineEyeInvisible size='2rem' /> : <AiOutlineEye size='2rem'/> }
                                  />
                                }
                                  />
                              </Flex>

                              <Flex alignItems='center' flexDir={['column', 'column', 'column', 'row']}>
                                  <FormInput 
                                  label="Re-type Password" 
                                  containerProps={{
                                    flexDir: 'column',
                                    mr:['0','0','0','3.9rem']
                                  }} 
                                  labelProps={{
                                    alignSelf: 'flex-start',
                                    borderRight: 'unset',
                                    fontSize: '1.1rem',
                                    fontWeight: '800'
                                  }}
                                  inputProps={{
                                    id:'password',
                                    type: passwordVisible ? 'text' : 'password',
                                    borderRadius:'md',
                                    border: `2px solid ${metallicSunburst} !important`,
                                    borderRight:'none !important',
                                    p: '2rem',
                                 
                                  }}
                                  inputRightAddon= {
                                  <InputRightAddon  
                                  onClick={(e) => togglePasswordVisiblity(e)}
                                  as='button'
                                  height='inherit'
                                  border={`2px solid ${metallicSunburst} !important`} 
                                  borderLeft='none !important'
                                  bg='transparent' 
                                  children={passwordVisible ? <AiOutlineEyeInvisible size='2rem' /> : <AiOutlineEye size='2rem'/> }
                                  />
                                }
                                  />
                                  <Btn mt={['1.5rem', '1.5rem', '1.5rem', '0']} p='1.2rem'  flex={0.9} alignSelf='flex-end'  type='submit'>Join Amahlubi</Btn>
                              </Flex>
                          </Stack>
                      </form>

                      <HeaderTag 
                          textTransform='uppercase'
                          letterSpacing='unset'
                          as='h3' 
                          fontSize='1.1rem'
                          textAlign='left' 
                          fontFamily='Montserrat'
                          fontWeight='semibold'
                          >
                            Already have an account? <Link href='/login'><a>Log in</a></Link>
                      </HeaderTag>
                    </Box>
                </Flex>
          </Wrapper>
      </Layout>
    </div>
  )
}

export default createaccount