import Head from "next/head";
import AmahlubistStyle from "@/components/Home/AmahlubistStyle";
import ContactSection from "@/components/ContactSection";
import CompleteProfile from "@/components/Dashboard/CompleteProfile";
import Footer from "@/components/Footer";
import Hero from "@/components/Home/Hero";
import Layout from "@/components/Layout";
import TheAmahlubist from "@/components/Home/TheAmahlubist";
import BuildingAnILO from "@/components/Home/BuildingAnILO";
import Welcome from "@/components/Home/Welcome";
import withAuth from "middleware/withAuth";
import { NextPageContext } from "next";
import { useEffect } from "react";
import { useSetRecoilState } from "recoil";
import { AuthAtom } from "recoilStore/AuthAtom";

export default function Home(props: any): JSX.Element {
  const setUser = useSetRecoilState(AuthAtom);

  useEffect(() => {
    if (props.initialRecoilState?.user) {
      setUser({
        token: props?.initialRecoilState?.user?.token,
        ...props?.initialRecoilState?.user,
      });
    }
  }, [props.initialRecoilState?.user]);

  return (
    <div>
      <Head>
        <title>Welcome - </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CompleteProfile />
      <Layout>
        <>
          <Hero />
          <Welcome />
          <TheAmahlubist />
          <BuildingAnILO />
          <AmahlubistStyle />
          <ContactSection />
          <Footer />
        </>
      </Layout>
    </div>
  );
}

export const getServerSideProps = withAuth(async (context: NextPageContext) => {
  let user = null;
  if (context.res["user"]) user = context.res["user"];

  return {
    props: {
      initialRecoilState: { user },
    },
  };
});
