import { Heading, Stack, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Hero from '../components/Home/Hero'
import Layout from '../components/Layout'

export default function Home():JSX.Element {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <Hero />
      </Layout>
    </div>
  )
}
