import {
  border,
  Box,
  Flex,
  Icon,
  InputLeftAddon,
  InputRightAddon,
  InputRightElement,
  Link,
  Stack,
  Text,
  useTheme,
} from "@chakra-ui/react";
import {
  AiOutlineEyeInvisible,
  AiOutlineEye,
  AiOutlineReload,
} from "react-icons/ai";
import { SyntheticEvent, useState } from "react";
import Head from "next/head";
import NextLink from "next/link";
import { useFormik } from "formik";
import * as yup from "yup";
import FormInput from "../components/Forms/FormInput";
import HeaderTag from "../components/HeaderTag";
import Layout from "../components/Layout";
import Wrapper from "../components/Wrapper";
import { Btn } from "../components/Button";
import { FaChevronRight } from "react-icons/fa";

function login() {
  const theme = useTheme();
  const { black, white } = theme.colors.brand;
  const [passwordVisible, setPasswordVisible] = useState(false);

  const validationSchema = yup.object().shape({
    email: yup.string().trim().email().required("Email Address is required"),
    password: yup.string().trim().required("Password is required"),
  });

  const {
    handleSubmit,
    handleChange,
    handleBlur,
    isSubmitting,
    errors,
    touched,
  } = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    validationSchema,
    onSubmit: async (values, formikHelpers) => {
      console.log(values);
    },
  });

  const togglePasswordVisiblity = (e: SyntheticEvent) => {
    e.preventDefault();
    setPasswordVisible(!passwordVisible);
  };

  return (
    <div>
      <Head>
        <title>Create Account - Amahlubi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Wrapper>
          <Flex
            justifyContent="center"
            alignItems="center"
            flexDir="column"
            pos="relative"
            zIndex={1}
          >
            <HeaderTag mb="1.8rem" fontWeight="600" letterSpacing="unset">
              Sigin into to your Account
            </HeaderTag>
            <Box
              bg="whiteAlpha.900"
              padding="5rem 3.2rem"
              borderRadius="lg"
              maxW="60.3rem"
              w="100%"
              mt="3rem"
            >
              <HeaderTag
                mt="unset"
                letterSpacing="unset"
                fontSize="1.7rem"
                mb="1.8rem"
                fontWeight="600"
                color="black"
              >
                Enter your login details
              </HeaderTag>
              <form onSubmit={handleSubmit}>
                <Stack spacing="2.7rem">
                  <Flex
                    alignItems="center"
                    flexDir={["column", "column", "column", "row"]}
                  >
                    <FormInput
                      // label="First Name"
                      containerProps={{
                        flexDir: "column",
                        // mr: ["0", "0", "0", "3.9rem"],
                      }}
                      labelProps={{
                        alignSelf: "flex-start",
                        borderRight: "unset",
                        fontSize: "1.1rem",
                        fontWeight: "800",
                      }}
                      inputProps={{
                        id: "email",
                        name: "email",
                        type: "email",
                        onChange: handleChange,
                        onBlur: handleBlur,
                        isInvalid: !!errors.email && touched.email,
                        borderRadius: "md",
                        border: `1px solid ${black} !important`,
                        p: "2.3rem",
                        color: black,
                        placeholder: "Email Address",
                        _placeholder: {
                          color: black,
                          fontWeight: "bold",
                        },
                      }}
                      formErrorMessage={errors.email}
                    />
                  </Flex>

                  <Flex alignItems="center" flexDir="column">
                    <FormInput
                      containerProps={{
                        flexDir: "column",
                      }}
                      labelProps={{
                        alignSelf: "flex-start",
                        borderRight: "unset",
                        fontSize: "1.1rem",
                        fontWeight: "800",
                      }}
                      inputProps={{
                        id: "password",
                        name: "password",
                        onChange: handleChange,
                        onBlur: handleBlur,
                        isInvalid: !!errors.password && touched.password,
                        placeholder: "Password",
                        type: passwordVisible ? "text" : "password",
                        borderRadius: "md",
                        border: `1px solid ${black} !important`,

                        p: "2.3rem",
                        color: black,
                        _placeholder: {
                          color: black,
                          fontWeight: "bold",
                        },
                      }}
                      formErrorMessage={errors.password}
                      inputRightAddon={
                        <InputRightElement
                          onClick={(e) => togglePasswordVisiblity(e)}
                          as="button"
                          height="100%"
                          mr="1rem"
                          bg="transparent"
                          color={black}
                          children={
                            passwordVisible ? (
                              <AiOutlineEyeInvisible size="2rem" />
                            ) : (
                              <AiOutlineEye size="2rem" />
                            )
                          }
                        />
                      }
                    />
                    <HeaderTag
                      alignSelf="flex-end"
                      letterSpacing="unset"
                      as="h3"
                      fontSize="1.1rem"
                      fontFamily="Montserrat"
                      fontWeight="semibold"
                      mt="1rem"
                      mb="1.4rem"
                      color="black"
                    >
                      <NextLink href="/password/reset">
                        <Link href="/password/reset">
                          <Icon mb="-0.2rem" mr=".2rem" as={AiOutlineReload} />
                          Reset forgotten password
                        </Link>
                      </NextLink>
                    </HeaderTag>
                  </Flex>

                  <Flex justifyContent="center">
                    <Btn
                      isLoading={isSubmitting}
                      type="submit"
                      fontFamily="Roboto"
                      fontWeight="400"
                      borderRadius="lg"
                      fontSize="1.2rem"
                      maxW="20.6rem"
                      w="100%"
                      textAlign="center"
                      bgColor={black}
                      color={white}
                      border={black}
                      px="1.8rem"
                      py="1.5rem"
                      // _hover={{ backgroundColor: "black", opacity: ".7" }}
                      rightIcon={<Icon as={FaChevronRight} />}
                    >
                      Log me in
                    </Btn>
                  </Flex>
                </Stack>
              </form>

              <NextLink href="/login">
                <Link href="/login">
                  <HeaderTag
                    color={black}
                    letterSpacing="unset"
                    as="h3"
                    fontSize="1.4rem"
                    fontFamily="Montserrat"
                  >
                    I don't have an account?
                    <Text ml=".3rem" fontWeight="bold" as="span">
                      <a>Sign me up</a>
                    </Text>
                  </HeaderTag>
                </Link>
              </NextLink>
            </Box>
          </Flex>
        </Wrapper>
      </Layout>
    </div>
  );
}

export default login;
